
exports.USER_NAME_ALREADY_REGISTERED = 'USER NAME ALREADY REGISTERED';

exports.EMAIL_ALREADY_REGISTERED = 'EMAIL ALREADY REGISTERED';

exports.SOMETHING_WHEN_WRONG = 'SOMETHING WHEN WRONG';

exports.SUCCESSFULLY = 'SUCCESSFULLY';

exports.TOKEN = 'TOKEN';

exports.ADMIN = 'ADMIN';

exports.USER = 'USER';

exports.AUTHORIZATION_REQUIRED = 'AUTHORIZATION REQUIRED';

exports.USER_ACCESS_DENIED = 'USER ACCESS DENIED';

exports.ADMIN_ACCESS_DENIED = 'ADMIN ACCESS DENIED';

exports.INVALID_EMAIL_OR_PASSWORD='INVALID EMAIL OR PASSWORD'

exports.THIS_ACCOUNT_IS_BLOCK='THIS ACCOUNT IS BLOCK'

exports.INVALID_USER_NAME_OR_PASSWORD='INVALID USER NAME OR PASSWORD'

exports.USER_NAME_ALREADY_REGISTERED = "USER NAME ALREADY REGISTERED"

exports.NOT_FOUND = 'NOT FOUND';

exports.DATABASE_CONNECTED = 'DATABASE CONNECTED';

exports.INTERNAL_SERVER_ERROR = 'INTERNAL SERVER ERROR';

exports.REFRESH_TOKEN_WAS_EXPIRED = 'REFRESH TOKEN WAS EXPIRED';

exports.ACCESS_TOKEN_WAS_EXPIRED = 'ACCESS TOKEN WAS EXPIRED';

exports.AUTHORIZATION_EXPIRE = 'AUTHORIZATION EXPIRE';



// exports.TIMESTAMP=moment(new Date()).tz('Asia/Bangkok').format('YYYY-MM-DDTHH:mm:ss')
